name: run-tests
on:
  - push
  - pull_request
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"

      - name: Get Packages
        run: npm i

      - name: Run Tests
        run: npm run test
